### ISSUE TITLE
侧滑不会回去是怎么回事呢

### ISSUE THREAD

**Issue by wananxin** [yydcdut/SlideAndDragListView#12]
我写了个  添加了一个右侧删除按钮   但是划出来不会划回去了  要一直按着划出去不离开屏幕再回来才会滑回来    我setOnSlideListener划出去和回来都会触发  请问有什么方法可以在onSlideClose里面调用嘛让我规避这个方法

**Comment by yydcdut** [comment]
@wananxin 
意思是你不需要onSlideClose?

**Comment by wananxin** [comment]
不是啊，这个滑回去不会吧侧滑出来的按钮带回去这个BUG怎么解决呢，

**Comment by yydcdut** [comment]
@wananxin 
代码已经更新，试试 `0.5.3`
