### ISSUE TITLE
当list item背景为透明时，滑动还是会显示Menu

### ISSUE THREAD

**Issue by RitzoneX** [yydcdut/SlideAndDragListView#13]
左右滑动的时候，list item背景会变成orange

**Comment by yydcdut** [comment]
我明白你的意思了，但是为什么要将背景设置透明呢

**Comment by yydcdut** [comment]
我明白你的意思了，但是为什么要将背景设置透明呢

**Comment by RitzoneX** [comment]
我的背景是png图片，图片有部分地方是透明的

**Comment by RitzoneX** [comment]
@yydcdut 刚发现当list item高度比较大时，拖动item时会不停跳动

**Comment by yydcdut** [comment]
@RitzoneX 
额，上周五我也发现一个类似这样的问题，这几天会解决。
至于背景那部分我不能理解，如果正常来讲item的背景png图片有些地方透明的话那么应该看高父View的颜色，产品就是那么定义的么？

**Comment by yydcdut** [comment]
@RitzoneX 
发生跳动的itemView的布局最外层是RelativeLayout吗？

**Comment by RitzoneX** [comment]
@yydcdut 最外层是FrameLayout

**Comment by RitzoneX** [comment]
@yydcdut 我把demo的height调大一些，让你试试http://fir.im/k3wn

**Comment by yydcdut** [comment]
@RitzoneX 
好的，谢谢，我已经明白咋回事了

**Comment by yydcdut** [comment]
@RitzoneX 
我已经整成横滑回去之后就隐藏掉Menu了，试试 `0.5.3`

**Comment by RitzoneX** [comment]
好的

**Comment by RitzoneX** [comment]
@yydcdut 新版本不能拖动item？

**Comment by yydcdut** [comment]
@RitzoneX 
可以啊，你那里拖动不了了？

**Comment by RitzoneX** [comment]
现在发现的问题是setOnDragListener必须先要setOnListItemLongClickListener，不然没效果

**Comment by yydcdut** [comment]
@RitzoneX 
对，当时设计这一块的时候我是这样考虑的，只有当达到长点击效果才能触发drag

**Comment by RitzoneX** [comment]
提个建议，apk自动生成文件可以不用git追踪，不然仓库体积会大得很快
