### ISSUE TITLE
长按时间1000ms觉得有点长了，可不可以留出接口让用户自己设置，灵活一些

### ISSUE THREAD

**Issue by fg607** [yydcdut/SlideAndDragListView#14]
个人见解，仅供参考。

**Comment by yydcdut** [comment]
这部分因为有些机型无法触发到长按，所以用还是用了 AdsListView 的长点击监听器，可以试试 `0.5.3`

**Comment by fg607** [comment]
感谢你的回复！
----- 原始邮件 -----
发件人：yydcdut notifications@github.com
收件人：yydcdut/SlideAndDragListView SlideAndDragListView@noreply.github.com
抄送人：fg607 fg607@sina.com,  Author author@noreply.github.com
主题：Re:_[yydcdut/SlideAndDragListView]_长按时间1000ms觉得有点长了，可不可以留出接口让用户自己设置，灵活一些_(#14)
日期：2016年06月18日 17点43分

这部分因为有些机型无法触发到长按，所以用还是用了 AdsListView 的长点击监听器，可以试试 0.5.3

&mdash;
