### ISSUE TITLE
为什么我设置长按时间无效？？

### ISSUE THREAD

**Issue by wushange** [yydcdut/SlideAndDragListView#15]
为什么我设置长按时间无效？？

**Comment by yydcdut** [comment]
我没有暴露长按时间的API啊。。你在代码里面改的吗？

**Comment by dingzhixiang** [comment]
@yydcdut   见过最负责的开源项目作者

**Comment by yydcdut** [comment]
@dingzhixiang 
么么哒

**Comment by dingzhixiang** [comment]
@yydcdut  所以，可以留个联系方式吗，有问题好请教你

**Comment by yydcdut** [comment]
@dingzhixiang 
378040621

**Comment by wushange** [comment]
@yydcdut 不是得，是我写错了 是长按item的事件，api里面有啊 setOnListItemLongClickListener 这个 可是没有触发啊?

**Comment by yuanhong2016** [comment]
为什么长按无效啊，请问解决了吗

**Comment by yydcdut** [comment]
@yuanhong2016 
还没，现在出现少量机型长按无效。
你那里是什么手机？

**Comment by yydcdut** [comment]
@yuanhong2016 
@wushge11 
代码已经更新，试试 `0.5.3`

**Comment by yuanhong2016** [comment]
@yydcdut 谢谢分享，之前用的是三星手机，长按无效
