### ISSUE TITLE
左滑删除后的bug

### ISSUE THREAD

**Issue by ironman6121** [yydcdut/SlideAndDragListView#17]
左滑删除item以后，会出现其他item再次左滑出现UI界面问题，多试几次就会出现

**Comment by yydcdut** [comment]
@ironman6121 
UI界面什么问题？Item布局不对还是什么？

**Comment by ironman6121** [comment]
@yydcdut 就是第四个button，SDLV with Different Menu点进去，然后随便左滑一个item，正常的出现一个有置顶啊，标记未读啊，删除的View，这时候，这个view是完整正常的；但是多删除几次，在多左滑几次，左滑出来的这个view就只能出现一半，还有一半是灰色的了，望解决。

**Comment by yydcdut** [comment]
@ironman6121 
代码已经更新，试试 `0.5.3`

**Comment by ironman6121** [comment]
@yydcdut 好一点， 然后多试几次，还是会出现这种情况

**Comment by yydcdut** [comment]
@ironman6121 
能说一下具体操作过程，比如在删除的时候进行了其他item的滑开的操作，或者ListView滑动的操作，或者其他手势操作？

**Comment by ironman6121** [comment]
@yydcdut 就是随机删除item的操作，不用其他滑动或者滑开的操作，然后删除的该行item的上面一行，多半会出现此状况

**Comment by yydcdut** [comment]
@ironman6121 
好的，复现了，谢谢

**Comment by yydcdut** [comment]
@ironman6121 
问题解决，试试 `0.5.4`

**Comment by ironman6121** [comment]
@yydcdut 亲测已修复
