### ISSUE TITLE
拖放怎么没有用啊

### ISSUE THREAD

**Issue by pzhihao** [yydcdut/SlideAndDragListView#19]

**Comment by yydcdut** [comment]
是demo中就不能拖放吗？
麻烦说一下机型

**Comment by pzhihao** [comment]
就是你文档上写的：slideAndDragListView.setOnDragListener(new SlideAndDragListView.OnDragListener() {},但是我用的时候没找到slideAndDragListView下面有OnDragListener啊，DragListView有实现。我就用DragListView的，就没有用啊，该怎么搞

**Comment by yydcdut** [comment]
额，SlideAndDragListView 继承 DragListView，所以能够访问到OnDragListener。
现在的处理逻辑是如果要拖动，同时得设置setOnListItemLongClickListener();
