### ISSUE TITLE
上啦加载，下拉刷新时setOnListItemClickListener有bug

### ISSUE THREAD

**Issue by 401885064** [yydcdut/SlideAndDragListView#2]
我使用com.aspsine.swipetoloadlayout.SwipeToLoadLayout在SlideAndDragListView的外层实现了上啦加载，下拉刷新功能，但发现ListView的item点击事件监听分不清是上下滑动还是点击事件！请在dispatchTouchEvent中添加上下滑动的判断

**Comment by yydcdut** [comment]
已更新至0.3.3，更新一下再试试呢。
`compile 'com.yydcdut.sdlv:sdlv:0.3.3@aar'`

**Comment by 401885064** [comment]
嗯，好的！

**Comment by BlainPeng** [comment]
listview的侧滑删除，目前看到的就你的和苹果最像。当滑出一个item的menu时，然后再点击已打开的item（不点击menu），能不能把menu关掉？目前只能把它滑回去或者点击其它的item

**Comment by yydcdut** [comment]
谢谢，我会尽快解决这个问题！

**Comment by yydcdut** [comment]
@BlainPeng 
已修正，更新至0.3.4。
`compile 'com.yydcdut.sdlv:sdlv:0.3.4@aar'`

**Comment by BlainPeng** [comment]
点击menu时，listview的item点击事件没有屏蔽掉

**Comment by yydcdut** [comment]
@BlainPeng 
Try again!
`compile 'com.yydcdut.sdlv:sdlv:0.3.5@aar'`

**Comment by tungnhuxua** [comment]
Hi @yydcdut 

i can disable listview ?? (item disable Slide and drag)
thanks you

**Comment by yydcdut** [comment]
@tungnhuxua 
如果不要Slide的话，在设置Menu的时候不要添加MenuItem，`wannaOver`参数设置为false，就跟正常的ListView一样了。
如果不要Drag的话，不要设置`setOnDragListener()`就可以了。

**Comment by tungnhuxua** [comment]
i see, but listview many item, item have type = true ->> item disable slide and drag, else item have type = false -> item slide and drag.
lib set all listview.
help! thanks sir..

**Comment by yydcdut** [comment]
@tungnhuxua 
try 0.4.0, i add viewtype in SDLV. Maybe now ,it can satisfy the needs of yours.

**Comment by tungnhuxua** [comment]
hi friend,
libs can't auto menu height, 
if i set height item listview auto, because data big or small -> auto height item
but, menu = new menu(height,Color,true),
menu no auto height together item on listview
how to fix, thanks you

**Comment by tungnhuxua** [comment]
libraries have properties not moving item. you help! thanks you

**Comment by yydcdut** [comment]
@tungnhuxua 
if you dont add `itemMenu` to `Menu`,item will not slide.

**Comment by yydcdut** [comment]
@tungnhuxua 
About height,try version 0.4.1.

**Comment by tungnhuxua** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9468773/12608553/53ea0aa6-c50f-11e5-9e2e-406af921d115.png)

example sir, help!!! thanks you.

**Comment by MFC2Android** [comment]
滑动显示了删除按钮后，不点击，再滑回去后，点击item没反应

**Comment by MFC2Android** [comment]
不能自定义菜单高度了？

**Comment by CodeMAI** [comment]
你好，咨询几个问题：
1.请问最新版本的在哪设置菜单高度。
2.请问能否禁止向右滑动，wannaOver参数设置为false的话,就没弹簧效果了
3.有个BUG:如果左边没Menu的话，向右滑动后，点击Item没反应；   或者右边有Menu，向左滑动后，不点击Menu，将其滑回去后，点击Item没反应

**Comment by yydcdut** [comment]
@401885064 
hi~
谢谢你的反馈。
1.菜单高度建议在布局里面固定。
如果设置高度和宽度为`wrap_content`的形式的话还是可以运行起来的，就跟正常的ListView一样。
2.你的意思是我只有右边有菜单，但是往右滑动的话还是会有弹簧效果这样情况吗？
如果是，我会尽快解决这个问题哈。不是的话希望能再讲详细点。
3.我复现了第一情况，第二个情况没有复现。希望能详细一点，谢谢。

**Comment by CodeMAI** [comment]
你好，补充我的反馈：
1.我的菜单最外层的LinearLayout在布局里面定义如下:
android:layout_width="match_parent"
android:layout_height="45dp"
但运行后，整条的item都很窄，我用的Adapter是SimpleAdapter。

2.对，左边没菜单，但还是能右滑出现弹簧效果。

3.第二种情况是，往左拖动，不松手，再往右隐藏menu，就点击不了item了

**Comment by caijiapeng0102** [comment]
你好，我想问下，点击效果(selector)，貌似被屏蔽了？怎么才能再次实现点击效果呢

**Comment by yydcdut** [comment]
@caijiapeng0102 
对，因为在滑出菜单的时候也会出现点击态，我还没有解决这个问题呢，我会尽快修复！

**Comment by yydcdut** [comment]
@MFC2Android 
已修正，更新到0.4.2。

**Comment by caijiapeng0102** [comment]
@yydcdut 直接使用SlideAndDragListView  在滚动的时候，同时会触发item的点击事件？这个怎么解决阿？

**Comment by yydcdut** [comment]
@caijiapeng0102 
频率高吗？
我这边没有复现

**Comment by caijiapeng0102** [comment]
@yydcdut 基本上都会阿，一上下拉，都会触发item点击事件

**Comment by caijiapeng0102** [comment]
只是单纯的引用这个SlideAndDragListView  然后height和width都是fill_parent

**Comment by yydcdut** [comment]
@caijiapeng0102 
但是我是在里面判断了滑动过程中不触发点击事件。。
方便给个联系方式么？

**Comment by ymx91** [comment]
你好。 侧滑删除item后，剩余的某些item 控件背景颜色会变化，设置背景颜色为空也不行，怎样设置删除后不改变其他item默认的背景颜色。

**Comment by yydcdut** [comment]
@ymx91 
已复现，我尽快解决这个问题！谢谢！

**Comment by ck0113** [comment]
你好，设置了setOnDragListener之后不能拖动，怎么才能拖动呢

**Comment by qinci** [comment]
你好，重写SlideAndDragListView，设置OnScrollListener不回调怎么解决

**Comment by yydcdut** [comment]
@qinci
调用setOnListScrollListener便可

**Comment by yydcdut** [comment]
@chukuan
Demo中还是你的项目中无法drag？

**Comment by yydcdut** [comment]
@caijiapeng0102 
@ymx91 
fix bug,try
`compile 'com.yydcdut.sdlv:sdlv:0.5.0-beta@aar'`
@qinci 
已经更新README

**Comment by ck0113** [comment]
是demo中的

**Comment by yydcdut** [comment]
@chukuan 
试试最新的看看呢
`compile 'com.yydcdut.sdlv:sdlv:0.5.0-beta@aar'`

**Comment by ck0113** [comment]
@yydcdut 不可以拖动，而且OnListItemLongClickListener 也监听不到，是不是在onTouchEvent事件里给remove掉了

**Comment by yydcdut** [comment]
@chukuan 
能否给个联系方式详聊。

**Comment by ck0113** [comment]
@yydcdut  1203319202
