### ISSUE TITLE
Drag n Drop not working in Motorola devices

### ISSUE THREAD

**Issue by GulyaniM** [yydcdut/SlideAndDragListView#23]
I have used com.yydcdut.sdlv.SlideAndDragListView library in listView for implementing swipe(to delete) and drag drop functionality(for re-ordering items).
Dragging will be activated on the onListItemLongClick. It is working fine on all the devices. 
But, in the motorola devices, onListItemLongClick() is not working or in some motorola devices it is taking so much time to respond.
Please suggest some solution.

**Comment by yydcdut** [comment]
I recode the drag & drop function, try 0.6.0-beta.
