### ISSUE TITLE
如何在adapter中获取每个条目菜单的item

### ISSUE THREAD

**Issue by hexiangbing** [yydcdut/SlideAndDragListView#24]
首先感谢博主分享，我现在有一个需求就是，右侧滑出的菜单是关注和完成两个选项，点击关注，就变成取消关注，所以我需要获取到这个菜单项，然后动态改变它的文字，请问博主，我怎么样可以获取到右侧菜单项。

**Comment by yydcdut** [comment]
@hexiangbing 
现在的做法是可以通过onMenuItemClick中的View变量，找到ImageView和TextView，然后更改

后面我尝试想想办法暴露出来吧

**Comment by hexiangbing** [comment]
好的，我试试看，打扰了，谢谢！

在 2016-11-17 11:28:49，"yydcdut" notifications@github.com 写道：

@hexiangbing
现在的做法是可以通过onMenuItemClick中的View变量，找到ImageView和TextView，然后更改

后面我尝试想想办法暴露出来吧

**Comment by GibsonCool** [comment]
楼主有个问题，我能否判断如果某个item符合我的要求了，我要使其关闭左右滑动的功能

**Comment by yydcdut** [comment]
@GibsonCool 
不好意思才看见
可以，单独设置viewtype，设置一个空的menu就行，不要有menuItem
