### ISSUE TITLE
can we stop sliding list view item for a particular item(position)?

### ISSUE THREAD

**Issue by ankitm099** [yydcdut/SlideAndDragListView#25]
can we stop sliding list view item for a particular item(position)?

**Comment by yydcdut** [comment]
Yes, use view type.

**Comment by ankitm099** [comment]
Where to pass this view type in the SimpleActitiy class.?

**Comment by yydcdut** [comment]
If you want to stop sliding some items, set these items' menu empty

**Comment by ankitm099** [comment]
Should I pass null on ... mMenu.add(null);

**Comment by yydcdut** [comment]
No, don't add anything, just empty.
