### ISSUE TITLE
侧滑删除item时，无法定位position

### ISSUE THREAD

**Issue by JacksonCheney** [yydcdut/SlideAndDragListView#26]
侧滑删除Item时加AlertDialog判断会出现先remove掉Item然后又出现Item并显示dialog,还有删除时无法定位position，只能按顺序删除，不是第一条Item时无法进行删除操作

**Comment by yydcdut** [comment]
等忙完公司的我提供一个remove的API出来

**Comment by yydcdut** [comment]
试试0.5.5
`slideAndDragListView.deleteSlideItem();`
