### ISSUE TITLE
OnItemDelete方法里面position定位只能是0

### ISSUE THREAD

**Issue by JacksonCheney** [yydcdut/SlideAndDragListView#27]
调用这个方法的时候只能从上到下删除，无法直接定位position.Log显示在其他position时没有调用这个方法

**Comment by yydcdut** [comment]
意思是OnItemDelete的参数position返回的一直是0吗？

**Comment by JacksonCheney** [comment]
我重新检查了一遍，是我自己把上面OnMenuItemClick方法里面的参数传错了，现在好了
