### ISSUE TITLE
拖拽排序问题太多

### ISSUE THREAD

**Issue by AndSync** [yydcdut/SlideAndDragListView#28]
1、拖拽排序的时候 item不应该左右可以移动
2、item竟然可以移动到app外面，应该在listview范围内移动
3、item 长按之后移动的时候 一个副本跟着手势移动，Listview 里面这一条不应该去掉吗？应该显示空白区域

**Comment by yydcdut** [comment]
谢谢，明白你的意思了~

**Comment by yydcdut** [comment]
fix, try 0.6.0-beta
