### ISSUE TITLE
SDLV的item布局最外层宽度必须为match_parent

### ISSUE THREAD

**Issue by Leu-Z** [yydcdut/SlideAndDragListView#30]
如果不是设置成match_parent而是wrap_content，否则menu就会显示为空白。

**Comment by yydcdut** [comment]
谢谢，我会尽快查明原因
如果最外层不是match_parent的话，需要怎么设置呢？一般情况下不都是match_parent吗？

**Comment by Leu-Z** [comment]
的确，一般都是match_parent的。不过也有需要自适应大小的时候吧。
我算歪打误撞不小心设置成wrap_content后才测出了这个bug的(ˉ▽￣～)。改成match_parent就没问题了
