### ISSUE TITLE
删除item的时候出现bug

### ISSUE THREAD

**Issue by guozhiqiang123** [yydcdut/SlideAndDragListView#36]
在删除item的时候，集合中的数据显示remove的位置是正确的，但是重新渲染后，在界面上又出现那条我想删的数据。测试了一下午，发现使用你demo中的adapter就不会出现问题，而我自己写一个几乎和你一模一样的适配器，就出现删除后重新渲染混乱的问题，我很懵逼。希望大神能给解决一下

**Comment by yydcdut** [comment]
用的最新版本的库吗？
