### ISSUE TITLE
如果能根据数据动态更改menuitem的属性就更加完美了

### ISSUE THREAD

**Issue by guozhiqiang123** [yydcdut/SlideAndDragListView#38]
比如，根据数据我想要一句代码更改menuitem的文字来表示不同的状态。或者menuitem的背景颜色。
我现在的做法是先removeItem原来的menuitem 再添加个新的，这样做感觉好麻烦。还是小萌新 如果大佬能让这个过程一句代码搞定就太完美了！

**Comment by yydcdut** [comment]
可以设置不同的viewType来实现
当需要改变的时候，将改行的viewType换一下，然后对应上你所需要展示的menu的样式
