### ISSUE TITLE
menu的构造函数不对

### ISSUE THREAD

**Issue by LazyFrom** [yydcdut/SlideAndDragListView#43]
并没有这个构造函数Menu menu0 = new Menu(new ColorDrawable(Color.WHITE), true, 0);
只有没带颜色参数的两个构造函数

**Comment by yydcdut** [comment]
恩，那个构造函数干掉了
我更新下README

**Comment by LazyFrom** [comment]
我现在开启menu可以拉过头（弹簧效果），那个拉过头的背景是黄色的，可以在哪里修改颜色呢？

**Comment by yydcdut** [comment]
android:listSelector="@null"

**Comment by LazyFrom** [comment]
谢谢
