### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by yinyoupoet** [yydcdut/SlideAndDragListView#47]
0.7版，假设listView一共有10项，最下面无法直接在屏幕上显示出来的那几个item显示的内容和第一条一样（也有可能是最新添加进来的一样，因为我的最新添加的默认在第一个），严重影响使用

**Comment by yydcdut** [comment]
有截图吗？
是直接使用了SDLV还是外面还套了一层下拉刷新的控件？

**Comment by yinyoupoet** [comment]
外套下拉刷新的组件会让它无法滑动，直接使用就出现上述问题，代码改掉了没截图了

**Comment by yydcdut** [comment]
已修正，试试0.7.1
