### ISSUE TITLE
How can I use the custom adapter ?

### ISSUE THREAD

**Issue by mob-rockstar** [yydcdut/SlideAndDragListView#48]
I tried to use the custom adapter class in this draglistview as followings
`public class EditCardsListAdapter extends BaseAdapter {`

`editCardsListAdapter = new EditCardsListAdapter(this, cardList, this);
        cardListView.setAdapter(editCardsListAdapter);`
`cardListView.setOnDragDropListener(this);`

Can you let me now how to use the custom adapter in your draglistview.
Thanks

**Comment by yydcdut** [comment]
You can see the demo app.
[SlideAndDragListViewActivity](https://github.com/yydcdut/SlideAndDragListView/blob/1f42c2676cd16fae1b07ef0f8ca5c7f4c932e04c/app/src/main/java/com/yydcdut/demo/SlideAndDragListViewActivity.java)
