### ISSUE TITLE
Observer com.yydcdut.sdlv.WrapperAdapter$1@1c26db5 was not registered.

### ISSUE THREAD

**Issue by xing609** [yydcdut/SlideAndDragListView#50]
这个是更新gradle 到4.1编译出现的问题。gradle 2.2编译时没有报错。能否fix 一下？

**Comment by yydcdut** [comment]
编译出错吗？看着像是运行时候出的crash之类的呢

**Comment by yydcdut** [comment]
试试新版本呢 `'com.yydcdut:sdlv:0.7.3'`

**Comment by xing609** [comment]
恩，是运行的时候，更新到0.7.3不报这个错了。
还有一个问题是我升级了sdk 跟gradle整体列表不能上下滑动了。我现升级的用的sdk版本如下：
 compileSdkVersion 27
 buildToolsVersion '27.0.3'
 gradle-4.1
 一样的代码，我没有改动，原来老的sdk:
  targetSdkVersion : 23,
  gradle-2.2
都是可以上下滑动的，也没报那个错。只是升级了sdk,更新了gradle ，现在集成到了项目，希望楼主可以早点fix 掉，十分感谢！

**Comment by yydcdut** [comment]
嗯嗯，能麻烦再开个issus不？
