### ISSUE TITLE
在下拉加载过程中，我们发现点击内部的swipemenu ，不能产生onitemclick 事件，此现象必现，并困扰我们很久了。

### ISSUE THREAD

**Issue by victor911111** [yydcdut/SlideAndDragListView#56]
测试环境：
手机：小米/华为
android 版本： 8.0
测试代码：作者官方demo
现象再现：在加载过程中就概率发生点击无效，特别是半拉加载的时候
跟踪代码：发现点击事件必须要产生onScrollStateChangedProxy ，但是当SwipeRefreshLayout 上拉加载后，就不出现 onScrollStateChangedProxy，而这时点击item，SlideAndDragListView 认为这是mIsScrolling==true
此问题已经困扰我们很久，但我们的非常喜欢这个控件
希望作者能够帮助解决

**Comment by yydcdut** [comment]
试下0.7.6吧

**Comment by victor911111** [comment]
dear yy
   非常感谢🙏，我明天测试下，在跟你同步结果

发自我的 iPhone

**Comment by victor911111** [comment]
Dear yy
	非常感谢，愿sideanddraglistview 早日被google 收录

Best Regards

李华
上海车盈网络科技有限公司
Shanghai Cheying Network Technology Co., Ltd.
Mobile No.: +(86) 13651670250
E_mail:       lh@ipatoo.com 
Web Site： www.ipatoo.com
